my_shop_admin:
    resource: "@MyShopAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

logout:
    path:   logout

my_shop_def:
    resource: "@MyShopDefBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"