login:
    path:     /login
    defaults: { _controller: MyShopAdminBundle:Login:login }

add_users:
    path:     /add/user
    defaults: { _controller: MyShopAdminBundle:User:addUser }

show_all_users:
    path:     /add/user/list
    defaults: { _controller: MyShopAdminBundle:User:showUsers }

show:
    path:     /
    defaults: { _controller: MyShopAdminBundle:Product:show }

admin_add:
    path:     /add
    defaults: { _controller: MyShopAdminBundle:Product:add }

delete:
    path:     /{id}/delete
    defaults: { _controller: MyShopAdminBundle:Product:delete }
    requirements:
      id: \d+

update:
    path:     /{id}/update
    defaults: { _controller: MyShopAdminBundle:Product:update}      
    requirements:
      id: \d+

list_by_category:
    path:     /category/{id_category}/list
    defaults: { _controller: MyShopAdminBundle:Product:listByCategory}  
    requirements:
        id_category: \d+ 

add_photo_for_product:
    path:      /add/photo/product/{idProduct}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:addPhoto}
    requirements:
        idProduct: \d+

show_photo_for_product:
    path:      /show/photo/product/{idProduct}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:show}
    requirements:
        idProduct: \d+      

delete_photo_for_product:
    path:      /delete/photo/product/{idPhoto}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:deletePhoto}
    requirements:
        idPhoto: \d+

update_photo_for_product:
    path:      /update/photo/product/{idPhoto}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:updatePhoto}
    requirements:
        idPhoto: \d+

add_category:
    path:     /add/category/{idParent}
    defaults: { _controller: MyShopAdminBundle:Category:add,idParent:null}

delete_category:
    path:     /{id_category}/delete/category
    defaults: { _controller: MyShopAdminBundle:Category:delete} 
    requirements:
      id_category: \d+
   
update_category:
    path:     /{id_category}/update/category
    defaults: { _controller: MyShopAdminBundle:Category:updateCategory} 
    requirements:
      id_category: \d+ 

list_category:
    path:     /list/category
    defaults: { _controller: MyShopAdminBundle:Category:list}    


loading_test_admin:
    path:   /loading/admin
    defaults: { _controller: MyShopAdminBundle:LoadingTestData:loadingAdmin}

loading_test_product:
    path:   /loading/product
    defaults: { _controller: MyShopAdminBundle:LoadingTestData:loadingProduct}
   