show:
    path:     /
    defaults: { _controller: MyShopAdminBundle:Product:show }


admin_add:
    path:     /add
    defaults: { _controller: MyShopAdminBundle:Product:add }

delete:
    path:     /{id}/delete
    defaults: { _controller: MyShopAdminBundle:Product:delete }
    requirements:
      id: \d+

update:
    path:     /{id}/update
    defaults: { _controller: MyShopAdminBundle:Product:update}      
    requirements:
      id: \d+

list_by_category:
    path:     /category/{id_category}/list
    defaults: { _controller: MyShopAdminBundle:Product:listByCategory}  
    requirements:
        id_category: \d+ 

add_photo_for_product:
    path:      /add/photo/product/{idProduct}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:addPhoto}
    requirements:
        idProduct: \d+

show_photo_for_product:
    path:      /show/photo/product/{idProduct}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:show}
    requirements:
        idProduct: \d+      

delete_photo_for_product:
    path:      /show/photo/product/{FileName}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:deletePhoto}
       

add_category:
    path:     /add/category
    defaults: { _controller: MyShopAdminBundle:Category:add}        

delete_category:
    path:     /{id_category}/delete/category
    defaults: { _controller: MyShopAdminBundle:Category:delete} 
    requirements:
      id_category: \d+
    

list_category:
    path:     /list/category
    defaults: { _controller: MyShopAdminBundle:Category:list}    

   