login:
    path:     /login
    defaults: { _controller: MyShopAdminBundle:Login:login }

add_users:
    path:     /add/user
    defaults: { _controller: MyShopAdminBundle:User:addUser }

show_all_users:
    path:     /add/user/list
    defaults: { _controller: MyShopAdminBundle:User:showUsers }

show:
    path:     /{page}
    defaults: { _controller: MyShopAdminBundle:Product:show , page: 1}
    requirements:
      page: \d+

admin_add:
    path:     /add
    defaults: { _controller: MyShopAdminBundle:Product:add }

delete:
    path:     /{id}/delete
    defaults: { _controller: MyShopAdminBundle:Product:delete }
    requirements:
      id: \d+

deleteAjax:
    path:     /{id}/deleteAjax
    defaults: { _controller: MyShopAdminBundle:Product:deleteAjax }
    requirements:
      id: \d+
    options:
      expose: true

product_info:
    path:     /product/{id}
    defaults: { _controller: MyShopAdminBundle:Product:productInfo}
    requirements:
          id: \d+

update:
    path:     /{id}/update
    defaults: { _controller: MyShopAdminBundle:Product:update}      
    requirements:
      id: \d+

list_by_category:
    path:     /category/list/{id_category}-{page}-{quantityProduct}
    defaults: { _controller: MyShopAdminBundle:Product:listByCategory, page: 1, quantityProduct: 4}
    requirements:
        id_category: \d+
        page: \d+
        quantityProduct: \d+


add_photo_for_product:
    path:      /add/photo/product/{idProduct}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:addPhoto}
    requirements:
        idProduct: \d+

show_photo_for_product:
    path:      /show/photo/product/{idProduct}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:show}
    requirements:
        idProduct: \d+      

delete_photo_for_product:
    path:      /delete/photo/product/{idPhoto}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:deletePhoto}
    requirements:
        idPhoto: \d+

update_photo_for_product:
    path:      /update/photo/product/{idPhoto}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:updatePhoto}
    requirements:
        idPhoto: \d+

update_major_photo_for_product_Ajax:
    path:      /update/majorphoto/product/{idPhoto}
    defaults: {  _controller: MyShopAdminBundle:PhotoForProduct:updateMajorPhotoAjax}
    requirements:
        idPhoto: \d+
    options:
      expose: true

add_category:
    path:     /add/category/{idParent}
    defaults: { _controller: MyShopAdminBundle:Category:add,idParent:null}

delete_category:
    path:     /{id_category}/delete/category
    defaults: { _controller: MyShopAdminBundle:Category:delete} 
    requirements:
      id_category: \d+
   
update_category:
    path:     /{id_category}/update/category
    defaults: { _controller: MyShopAdminBundle:Category:updateCategory} 
    requirements:
      id_category: \d+ 

list_category:
    path:     /list/category
    defaults: { _controller: MyShopAdminBundle:Category:list}    


loading_test_admin:
    path:   /loading/admin
    defaults: { _controller: MyShopAdminBundle:LoadingTestData:loadingAdmin}

loading_test_product:
    path:   /loading/product
    defaults: { _controller: MyShopAdminBundle:LoadingTestData:loadingProduct}

import_product_csv:
    path:   /import/csv
    defaults: { _controller: MyShopAdminBundle:Product:importProduct }

export_product_csv:
    path:   /export/csv
    defaults: { _controller: MyShopAdminBundle:Product:exportProducts }

pages_list:
    path:   /pages
    defaults: { _controller: MyShopAdminBundle:Pages:showPages }

page_add:
    path:   /page/add
    defaults: { _controller: MyShopAdminBundle:Pages:addPage }

page_update:
    path:   /page/update/{id}
    defaults: { _controller: MyShopAdminBundle:Pages:updatePage}
    requirements:
      id: \d+

page_delete:
    path:   /page/delete/{id}
    defaults: { _controller: MyShopAdminBundle:Pages:deletePage}
    requirements:
      id: \d+