services:
  myshop_admin.abstract_check:
    class: MyShop\AdminBundle\Services\AbstractCheck
    abstract: true
    arguments:
      - "%photo_type%"

  myshop_admin.checking_photo:
    class: MyShop\AdminBundle\Services\CheckingPhoto
    parent: "myshop_admin.abstract_check"

  myshop_admin.photo_name_generator:
    class: MyShop\AdminBundle\Services\GeneratorNameForPhoto

  myshop_admin.resize_photo:
    class: MyShop\AdminBundle\Services\ResizePhoto

  myshop_admin.upload_photo:
    class: MyShop\AdminBundle\Services\UploadPhotoService
    arguments:
      - "@myshop_admin.checking_photo"
      - "@myshop_admin.photo_name_generator"
    calls:
      - ["setPhotoDir",["%photo_dir%"]]

  myshop_admin.delete_photo:
      class: MyShop\AdminBundle\Services\PhotoDelete
      arguments:
        - "@doctrine.orm.default_entity_manager"
        - "%photo_dir%"

  myshop_admin.sending_letters:
      class: MyShop\AdminBundle\Services\SendingLetters
      arguments:
        - "%photo_dir%"
        - "@mailer"
        - "@twig"

  myshop_admin.my_twig_extension:
    class: MyShop\AdminBundle\TwigExtension\TwigExtension
    public: false
    tags:
      - { name: twig.extension }
    arguments:
      - "@doctrine.orm.entity_manager"

  add_data_product_for_import:
    class: MyShop\AdminBundle\Services\AddCSVProduct
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@myshop_admin.checking_photo"
      - "%photo_dir%"

  import-export_product:
    class: MyShop\AdminBundle\Services\ImportExportProduct
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@add_data_product_for_import"
      - "@myshop_admin.checking_photo"

  product_mapper:
    class: MyShop\AdminBundle\Mapper\ProductMapper
    arguments:
      - "@validator"
      - "@doctrine.orm.default_entity_manager"
      - "%photo_dir%"

  count_product:
    class: MyShop\AdminBundle\Services\CountProduct
    arguments:
     - "@doctrine.orm.default_entity_manager"

  sql_quary:
    class: MyShop\AdminBundle\Services\SqlQuery
    arguments:
     - "@doctrine.orm.entity_manager"
     - "@knp_paginator"

  major_photo_service:
    class: MyShop\AdminBundle\Services\MajorPhotoService
    arguments:
      - "@doctrine.orm.entity_manager"

  create_product_order:
      class: MyShop\AdminBundle\Services\CreateProductOrder
      arguments:
        - "@doctrine.orm.entity_manager"
        - "@myshop_admin.upload_photo"