services:
  myshop_admin.checking_photo:
    class: MyShop\AdminBundle\Services\CheckingPhoto 
    arguments:
      - "%photo_type%"

  myshop_admin.photo_name_generator:
    class: MyShop\AdminBundle\Services\GeneratorNameForPhoto