<?php

namespace MyShop\DefBundle\Repository;

/**
 * ListCustomerOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListCustomerOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
