<?php

namespace MyShop\DefBundle\Repository;

/**
 * PhotoForProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoForProductRepository extends \Doctrine\ORM\EntityRepository
{
}
