# homepage:
#     path:     /
#     defaults: { _controller: MyShopDefBundle:Default:index }

tel:
    path:     /{idtel}
    defaults: { _controller: MyShopDefBundle:Default:cont }
    requirements:
      idtel: \d+

create:
    path:     /create      
    defaults: { _controller: MyShopDefBundle:Default:createProduct }

showAll:    
    path:     /
    defaults: { _controller: MyShopDefBundle:Default:showAll}