tel:
    path:     /{idtel}
    defaults: { _controller: MyShopDefBundle:Default:cont }
    requirements:
      idtel: \d+

list_category:
    path:  /list/category
    defaults: { _controller: MyShopDefBundle:Default:listCategory }

create:
    path:     /create      
    defaults: { _controller: MyShopDefBundle:Default:createProduct }

showAll:    
    path:     /
    defaults: { _controller: MyShopDefBundle:Default:showAll}

product_info_:
    path: /product/{id}/info
    defaults: { _controller: MyShopDefBundle:Product:productInfo }
    requirements:
      id: \d+

registration_customer:
    path:  /registration
    defaults: { _controller: MyShopDefBundle:Customer:registrationCustomer }

login_customer:
    path:  /customer/login
    defaults: { _controller: MyShopDefBundle:Customer:loginCustomer }

confirm_customer:
    path: /confirm/user/{hash}
    defaults: { _controller: MyShopDefBundle:Customer:confirmCustomer}

logout_customer:
    path: /exit

show_order:
    path: /basket
    defaults: { _controller: MyShopDefBundle:Basket:showOrder }

add_to_basket:
    path: /add/product/{idProduct}/tobasket
    defaults: { _controller: MyShopDefBundle:Basket:addToBasket }
    requirements:
      idProduct: \d+

add_to_basket_Ajax:
    path: /add/{idProduct}/tobasket/ajax
    defaults: { _controller: MyShopDefBundle:Basket:addToBasketAjax }
    requirements:
      idProduct: \d+
    options:
        expose: true

delete_product_from_basket:
    path: /delete/product/{id}/from_basket
    defaults: { _controller: MyShopDefBundle:Basket:deleteProductFromOrder }
    requirements:
        id: \d+
    options:
        expose: true

recalculation_count_product:
   path: /recalculation/count/product
   defaults: { _controller: MyShopDefBundle:Basket:recalculationCount }
   methods: [POST]

confirm_order:
    path: /confirm/order
    defaults: { _controller: MyShopDefBundle:Basket:confirmOrder }

close_order:
    path: /close/order/{id}
    defaults: { _controller: MyShopDefBundle:Basket:closeOrder }
    requirements:
      id: \d+
    options:
            expose: true

history_orders_customer:
    path: /orders
    defaults: { _controller: MyShopDefBundle:Basket:historyOrders}

order_info_:
    path: /order/{id}
    defaults: {_controller: MyShopDefBundle:Basket:orderInfo}
    requirements:
      id: \d+

list_by_category_def:
    path:     /category/list/{id_category}-{page}-{quantityProduct}
    defaults: { _controller: MyShopDefBundle:Product:listByCategory, page: 1, quantityProduct: 4}
    requirements:
        id_category: \d+
        page: \d+
        quantityProduct: \d+

API_REST:
    path:   /api/{id}/rest
    defaults: { _controller: MyShopDefBundle:API/REST/Product:infoProduct}

API_REST_list:
    path:   /api/rest
    defaults: { _controller: MyShopDefBundle:API/REST/Product:infoProductList}

API_JSONRPC_list:
    path:   /api/json
    defaults: { _controller: MyShopDefBundle:API/JsonRPC/JsonRPC:JsonRPC}

client_GUZZLE:
    path:   /guzzle
    defaults: { _controller: MyShopDefBundle:Default:clientGuzzle}

search:
    path:  /search
    defaults: { _controller: MyShopDefBundle:Search:search}

my_pages:
    path:   /{pageURL}
    defaults: { _controller: MyShopDefBundle:Pages:index}