tel:
    path:     /{idtel}
    defaults: { _controller: MyShopDefBundle:Default:cont }
    requirements:
      idtel: \d+

create:
    path:     /create      
    defaults: { _controller: MyShopDefBundle:Default:createProduct }

showAll:    
    path:     /
    defaults: { _controller: MyShopDefBundle:Default:showAll}

API_REST:
    path:   /api/{id}/rest
    defaults: { _controller: MyShopDefBundle:API/REST/Product:infoProduct}

API_REST_list:
    path:   /api/rest
    defaults: { _controller: MyShopDefBundle:API/REST/Product:infoProductList}
